msg_blue() {
    printf "${blue}==>${bold} $1${all_off}\n"
}

all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"

_update() {
    msg_blue "Updating desktop MIME database..."
    update-desktop-database -q

    msg_blue "Updating icon cache..."
    xdg-icon-resource forceupdate --theme hicolor &>/dev/null
    gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_install() {
    _update
}

post_upgrade() {
    _update
}

post_remove() {
    _update
}
